#include<stdio.h>
#include<conio.h>

void quizc();

void main(void)
{
int userinp;
clrscr();
printf("\t\t\t--------------------------\n");
printf("\t\t\t|Welcome in Language Quiz|\n");
printf("\t\t\t--------------------------\n");

printf("1) C Quiz");
printf("\n2) Exit");
printf("\n\nEnter only 1 option please: ");
scanf("%d",&userinp);
clrscr();

switch(userinp)
{
 case 1:
 quizc();
 break;

 case 2:
 break;

 default:
 break;
}
getch();
}

void quizc(void)
{
 int userquiz,score=0,c[10];
 char ch[10];
 printf("\t\t\t|------------\n\t\t\t\tQuiz\n\t\t\t\t------------|");
 printf("\n\n\tThere are 10 Questions. How many you want to play?");
 printf("\n\tEnter here please: ");
 scanf("%d",&userquiz);
 clrscr();

 for(int i=0; i<userquiz; i++)
 {
	switch(i)
	{
		case 0:
		printf("\n|--------------|");
		printf("Question No. %d|",i+1);
		printf("|--------------|");
		printf("\n\nThere are ______ loops in C.");
		printf("\n\n\t1. 2\n\t2. 3\n\t3. 4\n\t4. 5");
		printf("\n\nEnter only 1 option here: ");
		scanf("%d",&c[i]);
		if(c[i] == 2)
		{
			score = score + 1;
			printf("Correct Answer.");
			getch();
			clrscr();
		}
		else
		{
			printf("\nAnswer Not Correct.");
			printf("\nCorrect Answer is \"3\".");
			getch();
			clrscr();
		}
		break;

		case 1:
		printf("\n|--------------|");
		printf("Question No. %d|",i+1);
		printf("|--------------|");
		printf("\n\nC Language has been developed by __________________.");
		printf("\n\n\t1. Martin Richards\n\t2. Bijarne Stroustrup\n\t3. Dennis Ritche\n\t4. Ken Thompson");
		printf("\n\nEnter only 1 option here: ");
		scanf("%d",&c[i]);
		if(c[i] == 3)
		{
			score = score + 1;
			printf("Correct Answer.");
			getch();
			clrscr();
		}
		else
		{
			printf("\nAnswer Not Correct.");
			printf("\nCorrect Answer is \"Dennis Ritche\".");
			getch();
			clrscr();
		}
		break;

		case 2:
		printf("\n|--------------|");
		printf("Question No. %d|",i+1);
		printf("|--------------|");
		printf("\n\nPointer holds _________________.");
		printf("\n\n\t1. Value of variable\n\t2. Address of variable\n\t3. Both\n\t4. Ken Always Null");
		printf("\n\nEnter only 1 option here: ");
		scanf("%d",&c[i]);
		if(c[i] == 2)
		{
			score = score + 1;
			printf("Correct Answer.");
			getch();
			clrscr();
		}
		else
		{
			printf("\nAnswer Not Correct.");
			printf("\nCorrect Answer is \"Address of Variable\".");
			getch();
			clrscr();
		}
		break;

		case 3:
		printf("\n|--------------|");
		printf("Question No. %d|",i+1);
		printf("|--------------|");
		printf("\n\nTo accept 100 different values into the array we require ___________.");
		printf("\n\n\t1. loop\n\t2. if condition\n\t3. function\n\t4. structure");
		printf("\n\nEnter only 1 option here: ");
		scanf("%d",&c[i]);
		if(c[i] == 1)
		{
			score = score + 1;
			printf("Correct Answer.");
			getch();
			clrscr();
		}
		else
		{
			printf("\nAnswer Not Correct.");
			printf("\nCorrect Answer is \"loop\".");
			getch();
			clrscr();
		}
		break;

		case 4:
		printf("\n|--------------|");
		printf("Question No. %d|",i+1);
		printf("|--------------|");
		printf("\n\nWhich of the following is allowed in a C Arithmatic Instruction?");
		printf("\n\n\t1. [ ]\n\t2. { }\n\t3. ( )\n\t4. None of these");
		printf("\n\nEnter only 1 option here: ");
		scanf("%d",&c[i]);
		if(c[i] == 3)
		{
			score = score + 1;
			printf("Correct Answer.");
			getch();
			clrscr();
		}
		else
		{
			printf("\nAnswer Not Correct.");
			printf("\nCorrect Answer is \"( )\".");
			getch();
			clrscr();
		}
		break;

		case 5:
		printf("\n|--------------|");
		printf("Question No. %d|",i+1);
		printf("|--------------|");
		printf("\n\nIs it possible to run program without main() function?");
		printf("\n\n\t1. Yes\n\t2. No\n\t3. I don't know");
		printf("\n\nEnter only 1 option here: ");
		scanf("%d",&c[i]);
		if(c[i] == 2)
		{
			score = score + 1;
			printf("Correct Answer.");
			getch();
			clrscr();
		}
		else
		{
			printf("\nAnswer Not Correct.");
			printf("\nCorrect Answer is \"No\".");
			getch();
			clrscr();
		}
		break;

		case 6:
		printf("\n|--------------|");
		printf("Question No. %d|",i+1);
		printf("|--------------|");
		printf("\n\nHow many main() function we can have in our project?");
		printf("\n\n\t1. 1\n\t2. 2\n\t3. No Limit\n\t4. Depends on compiler");
		printf("\n\nEnter only 1 option here: ");
		scanf("%d",&c[i]);
		if(c[i] == 1)
		{
			score = score + 1;
			printf("Correct Answer.");
			getch();
			clrscr();
		}
		else
		{
			printf("\nAnswer Not Correct.");
			printf("\nCorrect Answer is \"1\".");
			getch();
			clrscr();
		}
		break;

		case 7:
		printf("\n|--------------|");
		printf("Question No. %d|",i+1);
		printf("|--------------|");
		printf("\n\nIs it true that a function may have several declaration, but only one definition.");
		printf("\n\n\t1. True\n\t2. False\n\t3. I don't know");
		printf("\n\nEnter only 1 option here: ");
		scanf("%d",&c[i]);
		if(c[i] == 1)
		{
			score = score + 1;
			printf("Correct Answer.");
			getch();
			clrscr();
		}
		else
		{
			printf("\nAnswer Not Correct.");
			printf("\nCorrect Answer is \"1\".");
			getch();
			clrscr();
		}
		break;

		case 8:
		printf("\n|--------------|");
		printf("Question No. %d|",i+1);
		printf("|--------------|");
		printf("\n\nWhich programming language is more faster among these?");
		printf("\n\n\t1. Java\n\t2. PHP\n\t3. C\n\t4. Visual Basic");
		printf("\n\nEnter only 1 option here: ");
		scanf("%d",&c[i]);
		if(c[i] == 3)
		{
			score = score + 1;
			printf("Correct Answer.");
			getch();
			clrscr();
		}
		else
		{
			printf("\nAnswer Not Correct.");
			printf("\nCorrect Answer is \"C\".");
			getch();
			clrscr();
		}
		break;

		case 9:
		printf("\n|--------------|");
		printf("Question No. %d|",i+1);
		printf("|--------------|");
		printf("\n\nWhich of the following is executed by Preprocess?");
		printf("\n\n\t1. #include<stdio.h>\n\t2. return 0\n\t3. void main(int argc , char ** argv)\n\t4. None of above");
		printf("\n\nEnter only 1 option here: ");
		scanf("%d",&c[i]);
		if(c[i] == 1)
		{
			score = score + 1;
			printf("Correct Answer.");
			getch();
			clrscr();
		}
		else
		{
			printf("\nAnswer Not Correct.");
			printf("\nCorrect Answer is \"#include<stdio.h>\".");
			getch();
			clrscr();
		}
		break;
	}
 }


 getch();
 clrscr();
}